; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = main

[env:esp32-poe-iso]
platform = espressif32@^6.0.0
board = esp32-poe-iso
framework = espidf

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

board_build.partitions = partitions.csv

build_flags =
  -DSIMULATION_MODE

board_build.cmake_extra_args =
  -DCONFIG_BT_ENABLED=1
  -DCONFIG_BT_BLUEDROID_ENABLED=1
  -DCONFIG_BT_CLASSIC_ENABLED=1
  -DCONFIG_BT_SPP_ENABLED=1
  -DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=0
  -DCONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY=0
  -DCONFIG_BTDM_CTRL_MODE_BTDM=1

platform_packages =
  tool-cmake@^3.24.0
  tool-ninja
